#define TAPPING_TERM 160
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define TAPPING_DANCE_TERM 400
#define CUSTOM_QUIT_KEY_DELAY 270
#define CUSTOM_POWER_KEY_DELAY 800
#define OS_DETECTION_KEYBOARD_RESET

