SERIAL_DRIVER = vendor
AUDIO_DRIVER = pwm_hardware
POINTING_DEVICE_DRIVER = analog_joystick
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
MOUSE_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
MIDI_ENABLE = yes
